# Generated by Django 2.2.5 on 2022-04-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colling',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('current', models.CharField(default='대기', max_length=45)),
                ('call_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=45, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'colling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='counselor',
            fields=[
                ('co_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('profile', models.CharField(max_length=100, null=True)),
                ('onoff', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'counselor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cu_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('profile', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='star',
            fields=[
                ('star_id', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField()),
            ],
            options={
                'db_table': 'star',
                'managed': False,
            },
        ),
    ]
