# Generated by Django 3.2.10 on 2022-04-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calling',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('cu_name', models.CharField(max_length=45)),
                ('co_name', models.CharField(max_length=45)),
                ('current', models.CharField(default='대기', max_length=45)),
                ('call_date', models.DateField()),
                ('category', models.CharField(max_length=45, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'calling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='point',
            fields=[
                ('star_id', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField()),
            ],
            options={
                'db_table': 'point',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='colling',
        ),
        migrations.DeleteModel(
            name='star',
        ),
    ]
